### ISSUE TITLE
Type variable names are too localised

### ISSUE THREAD

**Issue by slindley** [links-lang/links#43]
Type variable names are local to individual types rather than whole error messages. The current implementation threads a renaming environment through the pretty-printer. It may be easier to do something more imperative.
# TODO
- [x] figure out why gripers are called several times even though only one error message is printed. **Answer:** this is caused by unification that tries to unify types and backtracks in case of failure. Sam says that unification throws exceptions containing error messages, these exceptions get caught and backtracking is done. Only the last one is printed. This is probably not what unification should be doing. Error messages should be generated lazily. See #85 
- [x] all gripers should have their code refactored: calls to `code`/`show_type` should be assigned to let-bindings. This ensures proper evaluation order. Otherwise, subsequent calls to `^` are evaluated right-to-left and if the calls are inlined then variables are generated backwards. **UPDATE** This does not seem to work as intended. Variables names are generated in reverse order anyway. The probable reason is that they are not generated lazily enough. Needs fixing.
- [x] figure out why `hide_fresh_type_vars` is enabled by default. This does not seem to me like a useful thing to do. Perhaps we should reconsider?
- [x] Documentation: describe each new function, explain motivation for refactoring gripers (proper evaluation order), describe mechanism of name generation
- [ ] Fix the bug where effect type variable is not printed in the error message.

**Comment by jstolarek** [comment]
Pasting Sam's more detailed instructions on how to demonstrate the problem:

Let's suppose we try to write a compose function with type:

```
((a) -e-> b, (b) -e-> c) -e-> (a) -e-> c
```

If we get the composition the right way round:

```
links> sig h : ((a) -e-> b, (b) -e-> c) -e-> (a) -e-> c
...... fun h(f, g)(x) {g(f(x))};
```
then it works fine:
```
h = fun : ((a) -b-> c, (c) -b-> d) -b-> (a) -b-> d
```
If we get the order of the functions wrong
```
links> sig h : ((a) -e-> b, (b) -e-> c) -e-> (a) -e-> c
...... fun h(f, g)(x) {f(g(x))};
```
then we get the following error message:
```
<stdin>:2: Type error: The function
    `g'
has type
    `(_) -> _'
while the arguments passed to it have types
    `_'
and the currently allowed effects are
    `|_'.
In expression: g(x).
```
This is actually exhibiting a slight variant of the problem. Because each type variable occurs only once in each type, the pretty-printer decides to display them all as `_`. We can disable this behaviour by switching off the `hide_fresh_type_vars` setting:

```
links> @set hide_fresh_type_vars off;
```

Now we get:

```
<stdin>:2: Type error: The function
    `g'
has type
    `(a) -b-> c'
while the arguments passed to it have types
    `a'
and the currently allowed effects are
    `|a'.
In expression: g(x).
```

which looks pretty weird, because the first two 'a's appear to match up.

If we enable display of raw type variables, then we can see what is really going on:

```
links> @set show_raw_type_vars on;
```

yields:

```
<stdin>:2: Type error: The function
    `g'
has type
    `(6903) -6902-> 6904'
while the arguments passed to it have types
    `6901'
and the currently allowed effects are
   `|6902'.
In expression: g(x).
```
Now it is clear that 6901 and 6903 are not in fact the same type - but the effects do match up as we'd hope.

**Comment by jstolarek** [comment]
Aside: why is `hide_fresh_type_vars` enabled by default? My instinct would be that this is a kind of thing that one always wants to be turned on. Since this is not the case I reckon that there must have been some sort of motivation for hiding type variables by default. I just can't figure out what that motivation was. Can someone please explain this?

**Comment by jstolarek** [comment]
Above is a preliminary implementation. It uses a hash table inside `Vars` module to persist variables across different fragments of the error message. Here's how the error message looks now:

```
Type error: The function
    `g'
has type
    `(u) -s-> v'
while the arguments passed to it have types
    `t'
and the currently allowed effects are
    `|s'.
In expression: g(x).
```

I am not entirely happy with that result. I would want the variable names to start with `a`. `b`, `c` and so on rather than with `u`. Clearly this need more thought but code review appreciated.

**Comment by jstolarek** [comment]
Note to self (mostly).

I see two ways of improving my current patch:

1. Generate names lazily only when they are need. The result should be that printed type variable names will start with `a` rather then with some later letter of the alphabet. I think this should be fairly simple.
2. The above proposal is IMO not satisfactory. I would want type variables in the error message to actually correspond to type variables that the user wrote in the type signature. This might be more difficult. I don't yet have an idea how to implement that.

**Comment by jstolarek** [comment]
I spent more time considering two ways of moving forward that I outlined above.

Regarding first option, ie. making type variable names starting from `a` rather than some middle letter of the alphabet, this should be fairly easy. I think it suffices to replace `string` naming the variable with `string option ref` that is initially set to `None`. If the variable needs to be printed we generate a name and update reference to be `Some name`. This requires a separate mutable counter to be used with `num_to_letters` (which should be extracted from `make_names` in `types.ml`).

Second option looks like lots of work. If my understanding of code is correct names of variables actually written in the source code are only discarded in `desugarTypes`. Keeping them would involve changing definition of `MetaTypeVar` and there would be tons of fallout changes in `Types` and `DesugarTypes`. I think the costs outweigh the benefits so I'll stick with first option.

@slindley, yell if you disagree.

**Comment by jstolarek** [comment]
I have updated #73 with the implementation of first option outlined above. However, it does not work as intended. `fun_apply` seems to be called four times, not once. I suspect this might have something to do with OCaml's evaluation rules. I would appreciate some help with understanding why that happens.

Note that with names stored as mutable references there is no longer need to have `Hashtbl`. We can safely revert to `IntMap`, but I decided to hold up with doing this until above issues are resolved.

And obviously more work is required to actually consider the patch finished. All gripers need to have calls to `code`/`show_type` extracted to ensure proper evaluation order. And of course all of the new code should be documented.

The more I think about the second option outlined in two above comments the more I am convinced that it would be too much work.

**Comment by jstolarek** [comment]
The code is now ready for review here: 485974cb363bdb146f64a268b9ab4cc3ec69b943. (There is also some preliminary code cleanup here: 9e98603ef88f4c903da3216cab4fcec875f605e2). I am yet to write the code documentation - hopefully this will be finished tomorrow.

The idea behind the solution is to have a [mutable hash table](https://github.com/links-lang/links/commit/485974cb363bdb146f64a268b9ab4cc3ec69b943#diff-074ef9fa05fea4aba9e34869afe83472R1350) shared between several calls to `show_type` done when pretty-printing types in an error message. The hash table [stores mutable references to names](https://github.com/links-lang/links/commit/485974cb363bdb146f64a268b9ab4cc3ec69b943#diff-074ef9fa05fea4aba9e34869afe83472R1519), which allows to [generate names lazily only when they are needed](https://github.com/links-lang/links/commit/485974cb363bdb146f64a268b9ab4cc3ec69b943#diff-074ef9fa05fea4aba9e34869afe83472R1547). That's all done in `types.ml`. Changes in `typeSugar.ml` are mostly fallout. These were required to enforce left-to-right evaluation order and since I was touching the code anyway I took the opportunity to reformat it slightly to make it easier to read (hopefully).

I am not 100% sure about one of my changes. I have modified gripers that report channel errors (see [here](https://github.com/links-lang/links/commit/485974cb363bdb146f64a268b9ab4cc3ec69b943#diff-9641ee131706be0aa8d861e6c75e96adR1019)). Previously they would not state what the expected type is. This was in contrast with other gripers, so I changed that. Is that ok?

**Comment by jstolarek** [comment]
I wrote the documentation. Patch is now ready for review as #73.

There is also a potential bug, but frankly speaking I'm not sure whether it is a bug or intended behaviour. Need to discuss with Sam.

BTW. Can I write tests where I expect to get particular error message from the compiler? I know I can write tests where I expect something on stderr, but I would want to expect multi-line error messages rather than one-line errors.

**Comment by jstolarek** [comment]
Ok, there definitely IS a serious bug - I just realized that Travis is failing. Will investigate.

**Comment by jstolarek** [comment]
Bug fixed. Now ready for review.
