### ISSUE TITLE
Figure out how to do a release

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#61]
There are several files in the repo related to preparing a release tarball: `checkfiles` and `make_release` scripts as well as `MANIFEST` and `COMANIFEST` data files. These are woefully out of date. `MANIFEST` and `COMANIFEST` mention files that no longer exist and omit files that exist. Files generated by `checkfiles` are not properly cleaned by `make clean` and are not ignored by git. These are all easy things to fix but the questions are whether the upcoming release will be made using these scripts and whether it is worth to invest time in fixing this? Perhaps it would make sense to make a release using OPAM?

Since this is about making a release I am assigning this to Gorgie milestone, but if anyone more knowledgeable than me thinks this is incorrect please remove the milestone.
# TODO
- [x] remove old scripts and data files from the repo: `checkfiles`, `MANIFEST`, `COMANIFEST`, `make_release`
- [x] remove `RELEASE-CHECKLIST`, but make sure relevant things are placed on the wiki
- [x] update contents of `INSTALL` file. Perhaps point to wiki?
- [x] create OPAM description file
- [x] verify that the package installs correctly with all the required data files (most importantly, `prelude.links`, but also user documentation)
- [x] check how to enable/disable database backends during installation with opam
- [x] check what happens when libraries required by database backends are installed in the system. Is the package automatically reinstalled with the new backend enabled?
- [ ] make sure the installation process and release process are described. Release should be described on the wiki [here](https://github.com/links-lang/links/wiki/Release-checklist). Installation should be described in `INSTALL` file (or perhaps on the wiki?) Also, the database backend wiki page needs to be updated.

**Comment by jstolarek** [comment]
Oh, and I forgot that `make_release` assumes that the project is stored in Subversion, not git. This would also need to be updated.

**Comment by jstolarek** [comment]
As part of making an official release we should:

  * [ ] assign version number to Links
  * [ ] Decide on a license and put LICENSE file in the repo

**Comment by fehrenbach** [comment]
2: It's GPL, see https://github.com/links-lang/links/blob/master/COPYING

**Comment by jstolarek** [comment]
Thanks. Marked as done. (1) and (3) remain.

**Comment by jstolarek** [comment]
Note to self: assuming we use opam to build and distribute a release I need to figure out how to enable particular database backends. Is it possible to pass extra flags to opam for conditional compilation based on oasis? Should we assume a default backend (postgres?) and if user wants a different one they need to build from source?

**Comment by fehrenbach** [comment]
This is the way I understand opam optional dependencies: (I could be wrong though)
 - If the optional dependency is already installed the package should use it to enable the feature that depends on it.
 - That would mean that to enable an optional feature the user has to install the package the feature depends on ...and possibly reinstall Links, but perhaps opam would rebuild links automatically, I'm not sure.

To me this *feels* backwards. I'd think that I want to install some package with some (optional) feature and opam should figure out what it needs to install. On the other hand, this is common in C-land. ./configure checks what is available and enables features accordingly.

If my interpretation is correct, we would have enable database backends conditionally on whether their supporting libraries are installed. With the Makefile we might be able to set POSTGRESQL_LIBDIR depending on whether `ocamlfind query postgresql` returns something. I know nothing about oasis.

**Comment by jstolarek** [comment]
> To me this feels backwards. I'd think that I want to install some package with some (optional) feature and opam should figure out what it needs to install.

I agree. The user should be able to say "Install Links with MySQL backend" and the build system should install all the required dependencies.

**Comment by yallop** [comment]
> perhaps opam would rebuild links automatically

Yes: If `links` has an optional dependency on `postgresql` then installing `postgresql` will trigger a `links` rebuild.

> The user should be able to say "Install Links with MySQL backend" and the build system should install all the required dependencies.

One way to achieve this is to have a `links-mqsql` package, separate from `links` (but with a dependency between the two), that depends on whatever is needed for MySQL support.

**Comment by fehrenbach** [comment]
How about we unconditionally depend on sqlite, to have one backend always available for easy installation and experimentation by non-serious Links users, and conditionally on the others?

That would mean that database support works out of the box (not sure the sqlite backend actually works). I don't think it's unreasonable to expect users to install the appropriate opam package to use other databases.
We might want to improve the error message when the backend is not found to tell the user what package to install.

**Comment by jstolarek** [comment]
Notes from today's meeting:

  * New Links version should probably be 0.6
  * We need a maintainer - see #75

**Comment by jstolarek** [comment]
Note to self: start a wiki page that gives a checklist of things to do before making a release.
Also, there is a file in the repo that has such a checklist but it is from times when SVN was used. It is probably best to delete the file and move any relevant contents to wiki.

**Comment by jstolarek** [comment]
Does anyone want to take up the task of writing an opam file for Links? If yes please assign yourself to this ticket. If no one volunteers I'll start working on this sometime next week.

**Comment by jstolarek** [comment]
Done - please review pull request. One remaining things is updating of the wiki but I will do that after the pull request is merged.
