### ISSUE TITLE
Set `sessions` branch as the default branch

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#67]
Several people told me "`sessions` branch is the default branch, we should set it as a default branch on github". I would find that very convenient - switching manually from `master` to `sessions` all the time when working with github is annoying. Is there any reason why this change has not been made? It should take less than a minute.
# TODO
- [x] tag `master` session as `pre-session-types` so that we can easily go back to version of Links before development of session types started.
- [x] switch temporarily to `sessions` branch as the main branch
- [x] merge `sessions` branch into `master`. Should be a simple fast-forward merge, since master has not been developed since then.
- [x] revert to `master` as the default

**Comment by jstolarek** [comment]
Conclusion from today's meeting is that we should probably merge `sessions` branch back into `master` at some point near the release. To be discussed further when Sam and Garrett return.

**Comment by jstolarek** [comment]
Oh, and we should also tag current master branch to have easy access to Links version prior to sessions work.

**Comment by jstolarek** [comment]
I have tagged `master` branch with `pre-session-types` tag, as suggested on our meeting last week. This will allow us to easily go back to version of Links before session types.

There was also a suggestion that instead of setting `sessions` as the default branch we should merge it back into `master`. While I agree that merging back to `master` is a Good Thing, I also vote that we temporarily set `sessions` as the main branch. It's a matter of 15 seconds and it will save us annoying manual switching to `sessions` branch when browsing the repo online or sending a pull request. Once we merge `sessions` to `master` we'll revert back to `master` as default.

**Comment by jstolarek** [comment]
Merging back into `master` was supposed to be done for the Gorgie release. Shall we do this?

**Comment by slindley** [comment]
Yes

**Comment by jstolarek** [comment]
I would like to merge `sessions` back into `master` - any objections?

**Comment by slindley** [comment]
Nope. Please go ahead.

**Comment by jstolarek** [comment]
I'd like to hear a "yes" from @dhil as well.

**Comment by dhil** [comment]
I am happy to have `sessions` merged into `master`. Please go ahead.

**Comment by jstolarek** [comment]
Done.
