### ISSUE TITLE
Decide which database backends we support

### ISSUE THREAD

**Issue by jstolarek** [links-lang/links#76]
At the moment there are five database backends in Links source code:
- PostgreSQL
- MySQL
- SQLite
- SQLite3
- MonetDB

Per today's discussion we should probably do some cleanup:
- Why are there two SQLite backends? Do we really need both?
- Do all backends support all the features of Links? James suggested that SQLite(3) might not support all the operations required for query shredding to work. Is this indeed the case? If so, how do we handle situations when query shredding is used with SQLite backend? Do we emit an error message or just crash unexpectedly?
- It was suggested that one of the backends is enabled by default in the Links distribution that is published to OPAM. Stefan suggested SQLite as it requires no extra setup and allows people to easily try out Links. James suggested PostgreSQL as the one we currently support the most.
- Is anyone using MonetDB backend?
# TODO
- [x] delete SQLite 2 backend if we don't plan on supporting it
- [x] see whether MonetDB backend works
- [ ] decide on a default backend and enable it in `_oasis` file
- [x] make sure that we get reasonable error messages when trying to use shredding with database engines that don't support all the features required by shredding to work.

**Comment by jamescheney** [comment]
>     Why are there two SQLite backends? Do we really need both?

The first one is for SQLite 2, which is incompatible (different OCaml interfacing libraries).  I don't think there is a reason to maintain the SQLite (2) version.


>     Do all backends support all the features of Links? James suggested that SQLite(3) might not support all the operations required for query shredding to work. Is this indeed the case? If so, how do we handle situations when query shredding is used with SQLite backend? Do we emit an error message or just crash unexpectedly?

Shredding has only been tested with Postgres, and I believe it relies on features that Postgres supports and MySQL/Sqlite may not.  I intend to add a run-time error if we try to use shredding with a query that refers to a non-Postgres DB (it would be more work to catch this statically, similarly to how we currently don't statically check that a query refers to tables all from the same DB.)

>     It was suggested that one of the backends is enabled by default in the Links distribution that is published to OPAM. Stefan suggested SQLite as it requires no extra setup and allows people to easily try out Links. James suggested PostgreSQL as the one we currently support the most.

I wasn't arguing that PostgreSQL would be a better defauly than SQLite - the latter has the advantage that all you need is the SQLite library, the database is just stored in a plain file and you don't have to install + configure a database.  This would be enough for a lot of toy applications.

>     Is anyone using MonetDB backend?

Not that I know of.  Moreover, I suspect MonetDB has probably changed enough since then that this code would need to be updated significantly.  OTOH, it would be interesting to see if we can run the shredding code on MonetDB at some point.

**Comment by jstolarek** [comment]
> The first one is for SQLite 2, which is incompatible (different OCaml interfacing libraries). I don't think there is a reason to maintain the SQLite (2) version.

For the record, Debian still comes with both SQLite 2 and 3. But I guess we could just drop support for the older version of SQLite.

**Comment by jstolarek** [comment]
Once we decide on a default backend we should enable it in our build system.

**Comment by jamescheney** [comment]
It looks like the sqlite (2) and mapi ibraries are not available in OPAM, while mysql, postgresql and sqlite3 are available as packages.  I suggest that we resolve this as follows:

- make postgresql the default
- keep the  conditional compilation for sqlite3 and mysql as an option for building from source code
- drop support for sqlite (2) and monetDB since th eneeded libraries are not in OPAM
- eventually it would also be nice to make the links OPAM package compile support for sqlite3 and/mr mysql if they are present too, but not necessary for now

Any objections to this plan?

**Comment by jstolarek** [comment]
Sounds good to me. I suspect that deciding on just on backend and having it enabled by default will greatly simplify the transition to OPAM.

**Comment by jstolarek** [comment]
I propose a minor amendment to the above plan: do not enable `postgresql` by default. I have managed to change the `Makefile` so that it picks up backend libraries available on the system and automatically enables the corresponding backends. In the OPAM file I have defined all the backend libraries as optional dependencies. With this setting user could install Links without any of the backends and if they later install one of the backends - say, `postgresql` - opam will pick it up and recompile Links with this backend enabled.

**Comment by jstolarek** [comment]
It seems that this ticket is almost done. One thing that remains is:

> make sure that we get reasonable error messages when trying to use shredding with database engines that don't support all the features required by shredding to work.

Or is this already done as well?

**Comment by jamescheney** [comment]
No, that is not done, but I just had in mind issuing a run-time error if the program attempts to perform shredding with databases other than Postgres.  Checking this statically would be harder.

**Comment by jamescheney** [comment]
Closed since I think we decided not to set a default backend or use oasis, and all the other parts are done.
